version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/nestjs

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_blog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: